### ISSUE TITLE
Development environment setup using docker compose is broken

### ISSUE THREAD

**Issue by siavashserver** [glfw/glfw.github.io#100]
Running `docker-compose up` gives following error:

```
glfwgithubio-jekyll_serve-1  | ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
glfwgithubio-jekyll_serve-1  | Configuration file: /srv/jekyll/_config.yml
glfwgithubio-jekyll_serve-1  |             Source: /srv/jekyll
glfwgithubio-jekyll_serve-1  |        Destination: /srv/jekyll/_site
glfwgithubio-jekyll_serve-1  |  Incremental build: disabled. Enable with --incremental
glfwgithubio-jekyll_serve-1  |       Generating...
glfwgithubio-jekyll_serve-1  |                     done in 72.624 seconds.
glfwgithubio-jekyll_serve-1  |                     Auto-regeneration may not work on some Windows versions.
glfwgithubio-jekyll_serve-1  |                     Please see: https://github.com/Microsoft/BashOnWindows/issues/216
glfwgithubio-jekyll_serve-1  |                     If it does not work, please upgrade Bash on Windows or run Jekyll with --no-watch.
glfwgithubio-jekyll_serve-1  |  Auto-regeneration: enabled for '/srv/jekyll'
glfwgithubio-jekyll_serve-1  |                     ------------------------------------------------
glfwgithubio-jekyll_serve-1  |       Jekyll 4.2.2   Please append `--trace` to the `serve` command
glfwgithubio-jekyll_serve-1  |                      for any additional information or backtrace.
glfwgithubio-jekyll_serve-1  |                     ------------------------------------------------
glfwgithubio-jekyll_serve-1  | <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- webrick (LoadError)
glfwgithubio-jekyll_serve-1  |  from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
glfwgithubio-jekyll_serve-1  |  from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
glfwgithubio-jekyll_serve-1  |  from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `require_relative'
glfwgithubio-jekyll_serve-1  |  from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `setup'
glfwgithubio-jekyll_serve-1  |  from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:100:in `process'
glfwgithubio-jekyll_serve-1  |  from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
glfwgithubio-jekyll_serve-1  |  from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
glfwgithubio-jekyll_serve-1  |  from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
glfwgithubio-jekyll_serve-1  |  from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
glfwgithubio-jekyll_serve-1  |  from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
glfwgithubio-jekyll_serve-1  |  from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
glfwgithubio-jekyll_serve-1  |  from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
glfwgithubio-jekyll_serve-1  |  from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
glfwgithubio-jekyll_serve-1  |  from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
glfwgithubio-jekyll_serve-1  |  from /usr/gem/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
glfwgithubio-jekyll_serve-1  |  from /usr/gem/bin/jekyll:25:in `load'
glfwgithubio-jekyll_serve-1  |  from /usr/gem/bin/jekyll:25:in `<main>'
glfwgithubio-jekyll_serve-1 exited with code 1
```

**Comment by siavashserver** [comment]
Pinning docker image version to `jekyll/jekyll:4.2.0` temporarily fixes the issue till there is an upstream fix.

Related issue: https://github.com/jekyll/jekyll/issues/9066
